Repository AY2324S2-CS2103T-W10-4/tp, pull requests merged in 2024-04, with the labels that each got.

#71 Update doc
  docs/UserGuide.md
  docs/images/MailFeature.png
  docs/images/MailtgFeature.png
  docs/images/addgroupFeature.png
  docs/images/deleteFeature.png
  docs/images/deletegroupFeature.png
  docs/images/editgroupFeature.png
  docs/images/mail_template.png
  docs/images/mailtg_template.png
  docs/index.md
  docs/mail_template.png
Labels: documentation

#74 Update tabs for groups
  src/main/java/seedu/address/ui/PersonAttendanceList.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonAttendanceList.fxml
Labels: type.story

#75 Update Attendance UI
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/ui/AttendanceRow.java
  src/main/java/seedu/address/ui/PersonAttendanceList.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonAttendanceList.fxml
Labels: type.story

#78 Update UG
  docs/UserGuide.md
  docs/images/MailFeature.png
  docs/images/MailtgFeature.png
  docs/images/UpdatedUI.png
  docs/images/addFeature.png
  docs/images/addgroupFeature.png
  docs/images/deleteFeature.png
  docs/images/deletegroupFeature.png
  docs/images/editgroupFeature.png
  docs/images/filterFeature.png
  docs/images/findFeature.png
  docs/images/mail_template.png
  docs/images/mailtg_template.png
  docs/images/markAttendance.png
Labels: documentation

#132 Update UGbugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/mailtgteleFeature.png
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Bug

#140 DG: Mail and mailtg sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/MailSequenceDiagram.puml
  docs/diagrams/MailtgSequenceDiagram.puml
  docs/images/MailSequenceDiagram.png
  docs/images/MailtgSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/MailTelegramCommand.java
Labels: documentation

#141 Update User Guide
  docs/UserGuide.md
  docs/team/stella-lye.md
Labels: documentation
