Repository AY2324S2-CS2103T-W10-4/tp, pull requests merged in 2024-03, with the labels that each got.

#12 Change stella image to png file
  docs/AboutUs.md
  docs/images/STELLA-LYE.jpg
  docs/images/stella_lye.png
  docs/team/stella_lye.md
Labels: documentation, priority.High

#18 Update DeveloperGuide
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#31 Update find command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: documentation, type.story, priority.Medium

#28 Update user guide
  docs/UserGuide.md
Labels: documentation, priority.Medium

#36 Update studentmajor
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/team/doyelee0313.md
  docs/team/jocelyn-soh.md
  docs/team/stella-lye.md
  docs/team/tohlh.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/MajorTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.story, priority.High

#46 Update uml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation, priority.High

#48 Update ug
  docs/UserGuide.md
  docs/images/UpdatedUI.png
  docs/images/addFeature.png
  docs/images/filterFeature.png
  docs/images/findFeature.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: documentation, priority.High, type.Task

#45 Update filter group
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/group/GroupContainsKeywordsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/group/GroupContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.story, priority.High

#51 Update mail broadcast
  README.md
  build.gradle
  docs/UserGuide.md
  docs/images/MailFeature.png
  src/main/java/seedu/address/logic/commands/MailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MailCommandParser.java
  src/test/java/seedu/address/logic/commands/MailCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MailCommandParserTest.java
Labels: type.story, priority.High

#53 Update message constraints
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/StudentPanel.png
  docs/images/TutorsContactsProLogo.png
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/MailCommandParser.java
  src/main/java/seedu/address/model/group/Group.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MailCommandParserTest.java
Labels: type.story, priority.High

#65 Update developer guide
  docs/DeveloperGuide.md
Labels: type.story

#64 Update DG with newly added Group model
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#61 Add tabs to the UI
  src/main/java/seedu/address/logic/commands/EditGroupCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/EditGroupCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
Labels: type.story

#63 Update mail window
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MailCommand.java
  src/main/java/seedu/address/ui/MailWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MailWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/MailCommandTest.java
Labels: type.Task
